AWSTemplateFormatVersion: '2010-09-09'
Description: Windows Instance Template

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the Key Pair to decrypt Windows instance password
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC Id created in the previous template
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select the Public Subnet Id created in the previous template
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Select one or more Security Groups created in the previous template
  LatestWindowsAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base
    Description: Latest Windows AMI Id

Resources:
  WindowsInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: WindowsInstanceRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
      DeletionPolicy: Retain

  WindowsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref WindowsInstanceRole

  WindowsInstanceRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Sub 'Windows-client-${AWS::StackName}'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:Get*'
              - 's3:List*'
            Resource: '*'
      Roles:
        - !Ref WindowsInstanceRole
      DeletionPolicy: Retain

  WindowsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SubnetId: !Ref Subnet
      SecurityGroupIds: !Ref SecurityGroupIds
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance
          